name: Test

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        run: npm install pnpm -g

      - name: Install devDependencies
        run: pnpm install

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: pnpm dev
          browser: chrome
